import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  console.log(sessionData);

  return (
    <>
      <Head>
        <title>Repositorio Icci</title>
        <meta name="Repositoro Icci" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!sessionData && (
          <button
            onClick={sessionData ? () => signOut() : () => signIn('google')}
            className='rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-black/20'>
            Sign in with Google
          </button>
        )} 
      </div>
    </>
  );
};

export default Home;

